/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientView;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author adityamulik
 */
public class PatientAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    BookAnAppointmentPanel patientPanel;    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private Organization organization;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public PatientAreaJPanel(JPanel userProcessContainer, UserAccount user, Network network, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = business;
        
        patientPanel = new BookAnAppointmentPanel(PatientWorkAreaContainer, system, this.user);
        PatientWorkAreaContainer.add(patientPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientMenuPanel = new javax.swing.JPanel();
        panelSelectionBg1 = new javax.swing.JPanel();
        lblBookApt = new javax.swing.JLabel();
        panelSelectionBg4 = new javax.swing.JPanel();
        lblOldAppt = new javax.swing.JLabel();
        PatientWorkAreaContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1230, 663));

        PatientMenuPanel.setBackground(new java.awt.Color(51, 51, 51));
        PatientMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSelectionBg1.setBackground(new java.awt.Color(0, 0, 0));

        lblBookApt.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblBookApt.setForeground(new java.awt.Color(204, 0, 51));
        lblBookApt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookApt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BookAnAppt.png"))); // NOI18N
        lblBookApt.setText("Book an Appointment");
        lblBookApt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBookAptMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookAptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg1Layout = new javax.swing.GroupLayout(panelSelectionBg1);
        panelSelectionBg1.setLayout(panelSelectionBg1Layout);
        panelSelectionBg1Layout.setHorizontalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblBookApt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg1Layout.setVerticalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBookApt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PatientMenuPanel.add(panelSelectionBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 290, 50));

        panelSelectionBg4.setBackground(new java.awt.Color(51, 51, 51));

        lblOldAppt.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblOldAppt.setForeground(new java.awt.Color(255, 255, 255));
        lblOldAppt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblOldAppt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BookAnAppt.png"))); // NOI18N
        lblOldAppt.setText("Older Appointments");
        lblOldAppt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOldApptMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOldApptMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg4Layout = new javax.swing.GroupLayout(panelSelectionBg4);
        panelSelectionBg4.setLayout(panelSelectionBg4Layout);
        panelSelectionBg4Layout.setHorizontalGroup(
            panelSelectionBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg4Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblOldAppt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg4Layout.setVerticalGroup(
            panelSelectionBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblOldAppt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PatientMenuPanel.add(panelSelectionBg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 290, 50));

        PatientWorkAreaContainer.setPreferredSize(new java.awt.Dimension(940, 663));
        PatientWorkAreaContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PatientMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientWorkAreaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientWorkAreaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBookAptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookAptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBookAptMouseClicked

    private void lblBookAptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookAptMousePressed
        // TODO add your handling code here:
        setStyleBookAppointment();
        
        PatientWorkAreaContainer.removeAll();
        
        BookAnAppointmentPanel bookApt = new BookAnAppointmentPanel(PatientWorkAreaContainer, system, user);                        
        PatientWorkAreaContainer.add("Book Appointment", bookApt);
    }//GEN-LAST:event_lblBookAptMousePressed

    private void lblOldApptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOldApptMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblOldApptMouseClicked

    private void lblOldApptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOldApptMousePressed
        // TODO add your handling code here:
        setStyleOldAppointment();
        PatientWorkAreaContainer.removeAll();
        OldAppointmentHistory oldApt = new OldAppointmentHistory(PatientWorkAreaContainer, system, user);
        PatientWorkAreaContainer.add("Old Appointment", oldApt);
    }//GEN-LAST:event_lblOldApptMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientMenuPanel;
    private javax.swing.JPanel PatientWorkAreaContainer;
    private javax.swing.JLabel lblBookApt;
    private javax.swing.JLabel lblOldAppt;
    private javax.swing.JPanel panelSelectionBg1;
    private javax.swing.JPanel panelSelectionBg4;
    // End of variables declaration//GEN-END:variables

    private void setStyleBookAppointment() {
        // Set Enterprise to RED
        lblBookApt.setForeground(new Color(204,0,51));
        lblBookApt.setFont(new Font("Lucida Grande", Font.BOLD, 20));
        
        panelSelectionBg1.setBackground(Color.black);       
    }
    
    private void setStyleOldAppointment() {
        // Set Enterprise to RED
        lblOldAppt.setForeground(new Color(204,0,51));
        lblOldAppt.setFont(new Font("Lucida Grande", Font.BOLD, 20));
        
        lblBookApt.setForeground(Color.white);
        lblBookApt.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
        
        panelSelectionBg4.setBackground(Color.black);
        panelSelectionBg1.setBackground(new Color(51, 51, 51));       
    }

    private void setStyleVaccination() {
   
        // Roll back others to white
        lblBookApt.setForeground(Color.white);
        lblBookApt.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
        
        panelSelectionBg1.setBackground(new Color(51, 51, 51));
    }

    private void setStylePrescription() {
        
        // Roll back others to white
        lblBookApt.setForeground(Color.white);
        lblBookApt.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
        
        panelSelectionBg1.setBackground(new Color(51, 51, 51));
    }

}
