/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.PatientView;

import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;
import Business.WorkQueue.WorkRequest;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author adityamulik
 */
public class PatientAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount user;
    
    public PatientAreaJPanel(JPanel userProcessContainer, UserAccount user, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PatientMenuPanel = new javax.swing.JPanel();
        panelSelectionBg1 = new javax.swing.JPanel();
        lblBookApt = new javax.swing.JLabel();
        panelSelectionBg2 = new javax.swing.JPanel();
        lblVaccination = new javax.swing.JLabel();
        panelSelectionBg3 = new javax.swing.JPanel();
        lblPrescriptions = new javax.swing.JLabel();
        PatientWorkAreaContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1230, 663));

        PatientMenuPanel.setBackground(new java.awt.Color(51, 51, 51));
        PatientMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSelectionBg1.setBackground(new java.awt.Color(0, 0, 0));

        lblBookApt.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblBookApt.setForeground(new java.awt.Color(204, 0, 51));
        lblBookApt.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblBookApt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BookAnAppt.png"))); // NOI18N
        lblBookApt.setText("Book an Appointment");
        lblBookApt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBookAptMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBookAptMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg1Layout = new javax.swing.GroupLayout(panelSelectionBg1);
        panelSelectionBg1.setLayout(panelSelectionBg1Layout);
        panelSelectionBg1Layout.setHorizontalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblBookApt, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg1Layout.setVerticalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblBookApt, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PatientMenuPanel.add(panelSelectionBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 50));

        panelSelectionBg2.setBackground(new java.awt.Color(51, 51, 51));

        lblVaccination.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblVaccination.setForeground(new java.awt.Color(255, 255, 255));
        lblVaccination.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblVaccination.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Vaccinations.png"))); // NOI18N
        lblVaccination.setText("Vaccinations & Injections");
        lblVaccination.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblVaccinationMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg2Layout = new javax.swing.GroupLayout(panelSelectionBg2);
        panelSelectionBg2.setLayout(panelSelectionBg2Layout);
        panelSelectionBg2Layout.setHorizontalGroup(
            panelSelectionBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblVaccination, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg2Layout.setVerticalGroup(
            panelSelectionBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblVaccination, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PatientMenuPanel.add(panelSelectionBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 290, 50));

        panelSelectionBg3.setBackground(new java.awt.Color(51, 51, 51));

        lblPrescriptions.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        lblPrescriptions.setForeground(new java.awt.Color(255, 255, 255));
        lblPrescriptions.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblPrescriptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Prescription.png"))); // NOI18N
        lblPrescriptions.setText("Refill Prescriptions");
        lblPrescriptions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblPrescriptionsMousePressed(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg3Layout = new javax.swing.GroupLayout(panelSelectionBg3);
        panelSelectionBg3.setLayout(panelSelectionBg3Layout);
        panelSelectionBg3Layout.setHorizontalGroup(
            panelSelectionBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg3Layout.createSequentialGroup()
                .addGap(0, 14, Short.MAX_VALUE)
                .addComponent(lblPrescriptions, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg3Layout.setVerticalGroup(
            panelSelectionBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblPrescriptions, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        PatientMenuPanel.add(panelSelectionBg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 50));

        PatientWorkAreaContainer.setPreferredSize(new java.awt.Dimension(940, 663));
        PatientWorkAreaContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PatientMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PatientWorkAreaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PatientMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PatientWorkAreaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblBookAptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookAptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblBookAptMouseClicked

    private void lblVaccinationMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVaccinationMousePressed
        // TODO add your handling code here:
        
        setStyleVaccination();
        
        PatientWorkAreaContainer.removeAll();
        
        VaccinationJPanel vaccPanel = new VaccinationJPanel(PatientWorkAreaContainer, system);                
        PatientWorkAreaContainer.add("vaccination", vaccPanel);
    }//GEN-LAST:event_lblVaccinationMousePressed

    private void lblPrescriptionsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPrescriptionsMousePressed
        // TODO add your handling code here:
        
        setStylePrescription();
        
        PatientWorkAreaContainer.removeAll();
        
        RefillPrescriptionsPanel refillPanel = new RefillPrescriptionsPanel(PatientWorkAreaContainer, system);       
        PatientWorkAreaContainer.add("prescriptions", refillPanel);
    }//GEN-LAST:event_lblPrescriptionsMousePressed

    private void lblBookAptMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBookAptMousePressed
        // TODO add your handling code here:
        setStyleBookAppointment();
        
        PatientWorkAreaContainer.removeAll();
        
        BookAnAppointmentPanel bookApt = new BookAnAppointmentPanel(PatientWorkAreaContainer, system);                        
        PatientWorkAreaContainer.add("Book Appointment", bookApt);
    }//GEN-LAST:event_lblBookAptMousePressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PatientMenuPanel;
    private javax.swing.JPanel PatientWorkAreaContainer;
    private javax.swing.JLabel lblBookApt;
    private javax.swing.JLabel lblPrescriptions;
    private javax.swing.JLabel lblVaccination;
    private javax.swing.JPanel panelSelectionBg1;
    private javax.swing.JPanel panelSelectionBg2;
    private javax.swing.JPanel panelSelectionBg3;
    // End of variables declaration//GEN-END:variables

    private void setStyleBookAppointment() {
        // Set Enterprise to RED
        lblBookApt.setForeground(new Color(204,0,51));
        lblBookApt.setFont(new Font("Lucida Grande", Font.BOLD, 20));
        
        // Roll back others to white
        lblPrescriptions.setForeground(Color.white);
        lblPrescriptions.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
        
        lblVaccination.setForeground(Color.white);
        lblVaccination.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
        
        panelSelectionBg1.setBackground(Color.black);
        panelSelectionBg2.setBackground(new Color(51, 51, 51));
        panelSelectionBg3.setBackground(new Color(51, 51, 51));        
    }

    private void setStyleVaccination() {
        // Set Enterprise to RED
        lblVaccination.setForeground(new Color(204,0,51));
        lblVaccination.setFont(new Font("Lucida Grande", Font.BOLD, 20));
        
        // Roll back others to white
        lblBookApt.setForeground(Color.white);
        lblBookApt.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
        
        lblPrescriptions.setForeground(Color.white);
        lblPrescriptions.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
        
        panelSelectionBg1.setBackground(new Color(51, 51, 51));
        panelSelectionBg2.setBackground(Color.black);
        panelSelectionBg3.setBackground(new Color(51, 51, 51));
    }

    private void setStylePrescription() {
        lblPrescriptions.setForeground(new Color(204,0,51));
        lblPrescriptions.setFont(new Font("Lucida Grande", Font.BOLD, 20));
        
        // Roll back others to white
        lblBookApt.setForeground(Color.white);
        lblBookApt.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
        
        lblVaccination.setForeground(Color.white);
        lblVaccination.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
      
        
        panelSelectionBg1.setBackground(new Color(51, 51, 51));
        panelSelectionBg2.setBackground(new Color(51, 51, 51));
        panelSelectionBg3.setBackground(Color.black);
    }

}
