/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.NurseRole;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JPanel;

/**
 *
 * @author adityamulik
 * @author shivanichavan
 * @author divyeshdarji
 * 
 */
public class NurseAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    ManageAppointmentsJPanel managePatients;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private Organization organization;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public NurseAreaJPanel(JPanel userProcessContainer, UserAccount user, Network network, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = business;
        
        managePatients = new ManageAppointmentsJPanel(NurseWorkAreaContainer, system, user);
        NurseWorkAreaContainer.add(managePatients);
        
        
//        manageNetworkPanel = new ManageNetworkJPanel(sysAdminWorkAreaContainer, system);
//        sysAdminWorkAreaContainer.add("network", manageNetworkPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sysAdminMenuPanel = new javax.swing.JPanel();
        panelSelectionBg1 = new javax.swing.JPanel();
        lblManagePatients = new javax.swing.JLabel();
        panelSelectionBg2 = new javax.swing.JPanel();
        lblManagePatients1 = new javax.swing.JLabel();
        NurseWorkAreaContainer = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1230, 663));

        sysAdminMenuPanel.setBackground(new java.awt.Color(51, 51, 51));
        sysAdminMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSelectionBg1.setBackground(new java.awt.Color(0, 0, 0));

        lblManagePatients.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblManagePatients.setForeground(new java.awt.Color(204, 0, 51));
        lblManagePatients.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblManagePatients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/network.png"))); // NOI18N
        lblManagePatients.setText("Manage Appointments");
        lblManagePatients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblManagePatientsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManagePatientsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg1Layout = new javax.swing.GroupLayout(panelSelectionBg1);
        panelSelectionBg1.setLayout(panelSelectionBg1Layout);
        panelSelectionBg1Layout.setHorizontalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblManagePatients, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg1Layout.setVerticalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManagePatients, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sysAdminMenuPanel.add(panelSelectionBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 50));

        panelSelectionBg2.setBackground(new java.awt.Color(0, 0, 0));

        lblManagePatients1.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblManagePatients1.setForeground(new java.awt.Color(255, 255, 255));
        lblManagePatients1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblManagePatients1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/network.png"))); // NOI18N
        lblManagePatients1.setText("Request Medicines");
        lblManagePatients1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblManagePatients1MousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblManagePatients1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg2Layout = new javax.swing.GroupLayout(panelSelectionBg2);
        panelSelectionBg2.setLayout(panelSelectionBg2Layout);
        panelSelectionBg2Layout.setHorizontalGroup(
            panelSelectionBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg2Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblManagePatients1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg2Layout.setVerticalGroup(
            panelSelectionBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblManagePatients1, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        sysAdminMenuPanel.add(panelSelectionBg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, -1, -1));

        NurseWorkAreaContainer.setPreferredSize(new java.awt.Dimension(940, 663));
        NurseWorkAreaContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sysAdminMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NurseWorkAreaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sysAdminMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NurseWorkAreaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblManagePatientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagePatientsMouseClicked
        // TODO add your handling code here: 
        setStyleAssignPatients();
        
        NurseWorkAreaContainer.removeAll();
        ManageAppointmentsJPanel manPat = new ManageAppointmentsJPanel(NurseWorkAreaContainer, system, user);
        NurseWorkAreaContainer.add("NurseWorkArea",manPat);
        
    }//GEN-LAST:event_lblManagePatientsMouseClicked

    private void lblManagePatientsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagePatientsMousePressed
        // TODO add your handling code here:
//        setStyleNetwork();
    }//GEN-LAST:event_lblManagePatientsMousePressed

    private void lblManagePatients1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagePatients1MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblManagePatients1MousePressed

    private void lblManagePatients1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblManagePatients1MouseClicked

        setStyleRequestPrescriptions();
        
        NurseWorkAreaContainer.removeAll();        
        RequestPrescriptionMedicines managePrescriptions = new RequestPrescriptionMedicines(NurseWorkAreaContainer, system, user);                        
        NurseWorkAreaContainer.add("managePrescriptions", managePrescriptions);
    }//GEN-LAST:event_lblManagePatients1MouseClicked

//    public void setStyleNetwork() {
//        // Set Enterprise to RED
//        lblManagePatients.setForeground(new Color(204,0,51));
//        lblManagePatients.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        panel.setForeground(Color.white);
//        panel.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
//        
//        lblOrganizations.setForeground(Color.white);
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblEmployees.setForeground(Color.white);
//        lblEmployees.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(Color.black);
//        panelSelectionBg2.setBackground(new Color(51, 51, 51));
//        panelSelectionBg3.setBackground(new Color(51, 51, 51));
//        panelSelectionBg4.setBackground(new Color(51, 51, 51));
//    }
//    
//    public void setStyleEnterprise() {
//        // Set Enterprise to RED
//        panel.setForeground(new Color(204,0,51));
//        panel.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        lblManagePatients.setForeground(Color.white);
//        lblManagePatients.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblOrganizations.setForeground(Color.white);
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblEmployees.setForeground(Color.white);
//        lblEmployees.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(new Color(51, 51, 51));
//        panelSelectionBg2.setBackground(Color.black);
//        panelSelectionBg3.setBackground(new Color(51, 51, 51));
//        panelSelectionBg4.setBackground(new Color(51, 51, 51));
//    }
//    
//    public void setStyleOrganization() {
//        // Set Enterprise to RED
//        lblOrganizations.setForeground(new Color(204,0,51));
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        lblManagePatients.setForeground(Color.white);
//        lblManagePatients.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
//        
//        panel.setForeground(Color.white);
//        panel.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblEmployees.setForeground(Color.white);
//        lblEmployees.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(new Color(51, 51, 51));
//        panelSelectionBg2.setBackground(new Color(51, 51, 51));
//        panelSelectionBg3.setBackground(Color.black);
//        panelSelectionBg4.setBackground(new Color(51, 51, 51));
//    }
//    
//    public void setStyleEmployee() {
//        // Set Enterprise to RED
//        lblEmployees.setForeground(new Color(204,0,51));
//        lblEmployees.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        lblManagePatients.setForeground(Color.white);
//        lblManagePatients.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panel.setForeground(Color.white);
//        panel.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblOrganizations.setForeground(Color.white);
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(new Color(51, 51, 51));
//        panelSelectionBg2.setBackground(new Color(51, 51, 51));
//        panelSelectionBg3.setBackground(new Color(51, 51, 51));
//        panelSelectionBg4.setBackground(Color.black);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel NurseWorkAreaContainer;
    private javax.swing.JLabel lblManagePatients;
    private javax.swing.JLabel lblManagePatients1;
    private javax.swing.JPanel panelSelectionBg1;
    private javax.swing.JPanel panelSelectionBg2;
    private javax.swing.JPanel sysAdminMenuPanel;
    // End of variables declaration//GEN-END:variables

    private void setStyleAssignPatients() {
        lblManagePatients.setForeground(new Color(204,0,51));
        lblManagePatients.setFont(new Font("Lucida Grande", Font.BOLD, 20));
    }
    
    private void setStyleRequestPrescriptions() {
        lblManagePatients.setForeground(new Color(204,0,51));
        lblManagePatients.setFont(new Font("Lucida Grande", Font.BOLD, 20));
    }

}
