/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Patient.Employee;
import Business.Role.Role;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adityamulik
 */
public class ManageEmployeesJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public ManageEmployeesJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        
        populateComboBox();
    }

    public void populateComboBox() {
        // Populate role types
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        rSTableMetro1 = new rojeru_san.complementos.RSTableMetro();
        kButton1 = new com.k33ptoo.components.KButton();
        txtCity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbBoxRoles = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 663));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSTableMetro1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "Name", "Address", "Mobile", "Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        rSTableMetro1.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setColorBordeFilas(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setColorBordeHead(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        rSTableMetro1.setColorFilasForeground1(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setColorFilasForeground2(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setColorSelBackgound(new java.awt.Color(204, 0, 51));
        rSTableMetro1.setFuenteFilas(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rSTableMetro1.setFuenteFilasSelect(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        rSTableMetro1.setFuenteHead(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        rSTableMetro1.setIntercellSpacing(new java.awt.Dimension(0, 0));
        rSTableMetro1.setRowHeight(32);
        jScrollPane1.setViewportView(rSTableMetro1);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 680, 220));

        kButton1.setText("Add Employee");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, -1, -1));

        txtCity.setBorder(null);
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 440, 370, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 470, 370, -1));

        jLabel1.setText("Role:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 500, -1, -1));

        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 400, -1, -1));

        cmbBoxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 320, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
//        system.getEmployeeDirectory().createEmployee();
        
    }//GEN-LAST:event_kButton1ActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBoxRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KButton kButton1;
    private rojeru_san.complementos.RSTableMetro rSTableMetro1;
    private javax.swing.JTextField txtCity;
    // End of variables declaration//GEN-END:variables
}
