/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.Enterprise.EnterpriseType;
import Business.Network.Network;
import Business.Patient.Employee;
import Business.Role.HospAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adityamulik
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system; 
        
        populateNetwork();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new rojeru_san.complementos.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        kButton1 = new com.k33ptoo.components.KButton();
        jLabel4 = new javax.swing.JLabel();
        adminTxtUserName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        adminTxtPassword = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        adminTxtName = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        cmbBoxEnterpriseList = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        networkCmbBox = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 663));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Manage Enterprise Admin Panel");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise", "Network", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNetwork.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorBordeFilas(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorBordeHead(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblNetwork.setColorFilasForeground1(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorFilasForeground2(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorSelBackgound(new java.awt.Color(204, 0, 51));
        tblNetwork.setFuenteFilas(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblNetwork.setFuenteFilasSelect(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblNetwork.setFuenteHead(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tblNetwork.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblNetwork.setRowHeight(32);
        jScrollPane1.setViewportView(tblNetwork);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 680, 150));

        jLabel3.setText("Password:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, -1, -1));

        jLabel1.setText("Enterprise Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 20));

        kButton1.setText("Add Employee");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, -1, -1));

        jLabel4.setText("Name:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, -1, -1));

        adminTxtUserName.setBorder(null);
        add(adminTxtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 460, 370, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 370, -1));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 370, -1));

        adminTxtPassword.setBorder(null);
        add(adminTxtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 520, 370, 30));

        jLabel5.setText("Username:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 460, -1, -1));

        adminTxtName.setBorder(null);
        add(adminTxtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 370, 30));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 370, -1));

        cmbBoxEnterpriseList.setBackground(new java.awt.Color(255, 255, 255));
        cmbBoxEnterpriseList.setFont(new java.awt.Font("SansSerif", 1, 13)); // NOI18N
        cmbBoxEnterpriseList.setForeground(new java.awt.Color(25, 56, 82));
        cmbBoxEnterpriseList.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxEnterpriseList, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 370, -1));

        jLabel6.setText("Network:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, 20));

        networkCmbBox.setBackground(new java.awt.Color(255, 255, 255));
        networkCmbBox.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        networkCmbBox.setForeground(new java.awt.Color(25, 56, 82));
        networkCmbBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        networkCmbBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                networkCmbBoxActionPerformed(evt);
            }
        });
        add(networkCmbBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 370, -1));
    }// </editor-fold>//GEN-END:initComponents

    public void populateNetwork() {
        
        networkCmbBox.removeAllItems();
        cmbBoxEnterpriseList.removeAllItems();
        
        for (Network network : system.getNetworkList()) {
            networkCmbBox.addItem(network);
        }
    }
    
    private void populateEnterpriseComboBox(Network network){
        cmbBoxEnterpriseList.removeAllItems();
        
        for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
            cmbBoxEnterpriseList.addItem(enterprise);
        }        
    }
    
    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        //        system.getEmployeeDirectory().createEmployee();

    }//GEN-LAST:event_kButton1ActionPerformed

    private void networkCmbBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_networkCmbBoxActionPerformed
        // TODO add your handling code here:
        
        Network n = (Network) networkCmbBox.getSelectedItem();
        
        if (n != null) {
            populateEnterpriseComboBox(n);
        }        
        
        String name = adminTxtName.getText();
        String userName = adminTxtUserName.getText();
        String password = String.valueOf(adminTxtPassword.getPassword());
        
        Employee employee = system.getEmployeeDirectory().createEmployee(name);
        
        Enterprise e = (Enterprise) cmbBoxEnterpriseList.getSelectedItem();
        
        System.out.println("CHECKKKKK ENTERPRISE TYPE" + e);
        
//        if (cmbBoxEnterpriseList.getSelectedItem().) {
            System.out.println("Hospital Admin");
//            system.getUserAccountDirectory().createUserAccount(userName, password, employee, new HospAdminRole());
//        }
        
        
    }//GEN-LAST:event_networkCmbBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminTxtName;
    private javax.swing.JPasswordField adminTxtPassword;
    private javax.swing.JTextField adminTxtUserName;
    private javax.swing.JComboBox cmbBoxEnterpriseList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private com.k33ptoo.components.KButton kButton1;
    private javax.swing.JComboBox networkCmbBox;
    private rojeru_san.complementos.RSTableMetro tblNetwork;
    // End of variables declaration//GEN-END:variables
}
