/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Network.Network;
import Business.Patient.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adityamulik
 */
public class ManageNetworkJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    JPanel container;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public ManageNetworkJPanel(JPanel container, EcoSystem system) {
        initComponents();
        kButton2UpdateCity.setVisible(false);
        this.container = container;
        this.system = system;
        
        populateNetworkTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new rojeru_san.complementos.RSTableMetro();
        kButton1AddCity = new com.k33ptoo.components.KButton();
        txtCity = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        kButton2UpdateCity = new com.k33ptoo.components.KButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 663));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Manage Network");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 920, -1));

        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "No", "City"
            }
        ));
        tblNetwork.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorBordeFilas(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorBordeHead(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblNetwork.setColorFilasForeground1(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorFilasForeground2(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorSelBackgound(new java.awt.Color(204, 0, 51));
        tblNetwork.setFuenteFilas(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblNetwork.setFuenteFilasSelect(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblNetwork.setFuenteHead(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tblNetwork.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblNetwork.setRowHeight(32);
        jScrollPane1.setViewportView(tblNetwork);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 920, 150));

        kButton1AddCity.setText("Add City");
        kButton1AddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1AddCityActionPerformed(evt);
            }
        });
        add(kButton1AddCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));

        txtCity.setBorder(null);
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 370, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, 370, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("City Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        kButton2UpdateCity.setText("Edit City");
        kButton2UpdateCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2UpdateCityActionPerformed(evt);
            }
        });
        add(kButton2UpdateCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 480, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1AddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1AddCityActionPerformed
        // TODO add your handling code here:
        String city = txtCity.getText();
        
        Network network = system.createAndAddNetwork();
        network.setName(city);
        JOptionPane.showMessageDialog(null, "City Added Successfully");
        populateNetworkTable();
    }//GEN-LAST:event_kButton1AddCityActionPerformed

    private void kButton2UpdateCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2UpdateCityActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblNetwork.getSelectedRow();
        if (selectedRow >= 0)
        {
//            Network selectedNetwork = (Network) tblNetwork.getValueAt(selectedRow, 1);
//            SystemAdminUpdateCustomer fs = new SystemAdminUpdateCustomer(userProcessContainerSAMC, selectedCustomer, ecosystem);
//            userProcessContainerSAMC.add("SysAdminUpdateEmployees", fs);
//            CardLayout layout = (CardLayout) userProcessContainerSAMC.getLayout();
//            layout.next(userProcessContainerSAMC);
        }
    }//GEN-LAST:event_kButton2UpdateCityActionPerformed

    public void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel)tblNetwork.getModel();                       
        model.setRowCount(0);
        
        for (Network n: system.getNetworkList()) {
            Object[] row = new Object[2];
            row[0] = n.getCount();
            row[1] = n.getName();
            
            model.addRow(row);
        }                        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private com.k33ptoo.components.KButton kButton1AddCity;
    private com.k33ptoo.components.KButton kButton2UpdateCity;
    private rojeru_san.complementos.RSTableMetro tblNetwork;
    private javax.swing.JTextField txtCity;
    // End of variables declaration//GEN-END:variables
}
