/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Patient.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adityamulik
 */
public class ManageEnterpriseAdminJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public ManageEnterpriseAdminJPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNetwork = new rojeru_san.complementos.RSTableMetro();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbBoxRoles = new javax.swing.JComboBox<>();
        kButton1 = new com.k33ptoo.components.KButton();
        cmbBoxRoles1 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 663));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Manage Enterprise Admin Panel");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, -1, -1));

        tblNetwork.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise", "Network", "Admin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNetwork.setColorBackgoundHead(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorBordeFilas(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorBordeHead(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tblNetwork.setColorFilasForeground1(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorFilasForeground2(new java.awt.Color(204, 0, 51));
        tblNetwork.setColorSelBackgound(new java.awt.Color(204, 0, 51));
        tblNetwork.setFuenteFilas(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblNetwork.setFuenteFilasSelect(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        tblNetwork.setFuenteHead(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        tblNetwork.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblNetwork.setRowHeight(32);
        jScrollPane1.setViewportView(tblNetwork);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 680, 150));

        jLabel3.setText("Username:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, -1));

        jLabel1.setText("Enterprise Name:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, 20));

        cmbBoxRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxRoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 320, 40));

        kButton1.setText("Add Employee");
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });
        add(kButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        cmbBoxRoles1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbBoxRoles1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 320, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        //        system.getEmployeeDirectory().createEmployee();

    }//GEN-LAST:event_kButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbBoxRoles;
    private javax.swing.JComboBox<String> cmbBoxRoles1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private com.k33ptoo.components.KButton kButton1;
    private rojeru_san.complementos.RSTableMetro tblNetwork;
    // End of variables declaration//GEN-END:variables
}
