/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.LabDealerWorkArea;

import userinterface.PharmacyWorkArea.*;
import userinterface.DoctorWorkArea.*;
import userinterface.SystemAdminWorkArea.*;
import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Patient.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author adityamulik
 */
public class LabDealerAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    
    ManageLabJPanel manageLabJPanel;
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private Organization organization;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public LabDealerAreaJPanel(JPanel userProcessContainer, UserAccount user, Network network, Organization organization, Enterprise enterprise, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.user = user;
        this.organization = organization;
        this.enterprise = enterprise;
        this.network = network;
        this.system = business;
        manageLabJPanel = new ManageLabJPanel(pharmacyWorkPanel, system, this.enterprise, this.user);
        pharmacyWorkPanel.add("network", manageLabJPanel);
    }
    
    public LabDealerAreaJPanel() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pharmacyMenuPanel = new javax.swing.JPanel();
        panelSelectionBg1 = new javax.swing.JPanel();
        lblNetwork = new javax.swing.JLabel();
        pharmacyWorkPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(1230, 663));

        pharmacyMenuPanel.setBackground(new java.awt.Color(51, 51, 51));
        pharmacyMenuPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelSelectionBg1.setBackground(new java.awt.Color(0, 0, 0));

        lblNetwork.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        lblNetwork.setForeground(new java.awt.Color(204, 0, 51));
        lblNetwork.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/network.png"))); // NOI18N
        lblNetwork.setText("Manage Vitals Request");
        lblNetwork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNetworkMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNetworkMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelSelectionBg1Layout = new javax.swing.GroupLayout(panelSelectionBg1);
        panelSelectionBg1.setLayout(panelSelectionBg1Layout);
        panelSelectionBg1Layout.setHorizontalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSelectionBg1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSelectionBg1Layout.setVerticalGroup(
            panelSelectionBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNetwork, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pharmacyMenuPanel.add(panelSelectionBg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 50));

        pharmacyWorkPanel.setPreferredSize(new java.awt.Dimension(940, 663));
        pharmacyWorkPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pharmacyMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pharmacyWorkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pharmacyMenuPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 663, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pharmacyWorkPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblNetworkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNetworkMouseClicked
        // TODO add your handling code here:                
    }//GEN-LAST:event_lblNetworkMouseClicked

    private void lblNetworkMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNetworkMousePressed
        // TODO add your handling code here:
//        setStyleNetwork();
        
        pharmacyWorkPanel.removeAll();
        
        ManageNetworkJPanel manageNetwork = new ManageNetworkJPanel(pharmacyWorkPanel, system);                        
        pharmacyWorkPanel.add("network", manageNetwork);
    }//GEN-LAST:event_lblNetworkMousePressed

//    public void setStyleNetwork() {
//        // Set Enterprise to RED
//        lblNetwork.setForeground(new Color(204,0,51));
//        lblNetwork.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        panel.setForeground(Color.white);
//        panel.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
//        
//        lblOrganizations.setForeground(Color.white);
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblEmployees.setForeground(Color.white);
//        lblEmployees.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(Color.black);
//        panelSelectionBg2.setBackground(new Color(51, 51, 51));
//        panelSelectionBg3.setBackground(new Color(51, 51, 51));
//        panelSelectionBg4.setBackground(new Color(51, 51, 51));
//    }
    
//    public void setStyleEnterprise() {
//        // Set Enterprise to RED
//        panel.setForeground(new Color(204,0,51));
//        panel.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        lblNetwork.setForeground(Color.white);
//        lblNetwork.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblOrganizations.setForeground(Color.white);
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblEmployees.setForeground(Color.white);
//        lblEmployees.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(new Color(51, 51, 51));
//        panelSelectionBg2.setBackground(Color.black);
//        panelSelectionBg3.setBackground(new Color(51, 51, 51));
//        panelSelectionBg4.setBackground(new Color(51, 51, 51));
//    }
    
//    public void setStyleOrganization() {
//        // Set Enterprise to RED
//        lblOrganizations.setForeground(new Color(204,0,51));
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        lblNetwork.setForeground(Color.white);
//        lblNetwork.setFont(new Font("Lucida Grande", Font.PLAIN, 20));        
//        
//        panel.setForeground(Color.white);
//        panel.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblEmployees.setForeground(Color.white);
//        lblEmployees.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(new Color(51, 51, 51));
//        panelSelectionBg2.setBackground(new Color(51, 51, 51));
//        panelSelectionBg3.setBackground(Color.black);
//        panelSelectionBg4.setBackground(new Color(51, 51, 51));
//    }
    
//    public void setStyleEmployee() {
//        // Set Enterprise to RED
//        lblEmployees.setForeground(new Color(204,0,51));
//        lblEmployees.setFont(new Font("Lucida Grande", Font.BOLD, 20));
//        
//        // Roll back others to white
//        lblNetwork.setForeground(Color.white);
//        lblNetwork.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panel.setForeground(Color.white);
//        panel.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        lblOrganizations.setForeground(Color.white);
//        lblOrganizations.setFont(new Font("Lucida Grande", Font.PLAIN, 20));
//        
//        panelSelectionBg1.setBackground(new Color(51, 51, 51));
//        panelSelectionBg2.setBackground(new Color(51, 51, 51));
//        panelSelectionBg3.setBackground(new Color(51, 51, 51));
//        panelSelectionBg4.setBackground(Color.black);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblNetwork;
    private javax.swing.JPanel panelSelectionBg1;
    private javax.swing.JPanel pharmacyMenuPanel;
    private javax.swing.JPanel pharmacyWorkPanel;
    // End of variables declaration//GEN-END:variables
}
