/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.Authentication;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Patient.Employee;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author adityamulik
 */
public class Login extends javax.swing.JPanel {

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    
    JPanel container;
    private EcoSystem system;
    private UserAccount user;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    
    public Login(JPanel container) {
        initComponents();
        this.container = container;
        system = dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtUserName = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();

        setPreferredSize(new java.awt.Dimension(1230, 663));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 440, -1, -1));
        add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 320, 50));
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 350, 320, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        CardLayout layout = (CardLayout) container.getLayout();
        
        if (txtUserName.getText().equals("") || txtPassword.getPassword().equals("")) {
           JOptionPane.showMessageDialog(null, "Please enter the required fields!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            user = system.getUserAccountDirectory().authenticateUser(txtUserName.getText(), String.valueOf(txtPassword.getPassword()));                
            if(user == null) {
                JOptionPane.showMessageDialog(null, "Please enter correct Username and Password!", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            } else {
                 if(user.getRole().toString() == "Business.Role.SystemAdminRole") {
                    System.out.println("This is sys admin!");
                    Employee e = user.getEmployee();   
//                    System.out.println(e);   
                    
                    container.add("workArea", user.getRole().createWorkArea(container, user, system));
                    layout.next(container);
                } else if (user.getRole().toString() == "Business.Role.PatientRole") {
                    System.out.println("This is patient role");
                    
                    container.add("workArea", user.getRole().createWorkArea(container, user, system));
                    layout.next(container);
                }
            }
        }          
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
